//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rosnando_semG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animais
    {
        public int animal_id { get; set; }
        public string animal_nome { get; set; }
        public Nullable<int> animal_raca_id { get; set; }
        public int usuario_id { get; set; }
        public int status_animal_id { get; set; }
        public int tipo_animal_id { get; set; }
    
        public virtual RacaAnimal RacaAnimal { get; set; }
        public virtual StstusAnimal StstusAnimal { get; set; }
        public virtual TipoAnimal TipoAnimal { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
