//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rosnando_semG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A41AF6_rosnandoEntities : DbContext
    {
        public DB_A41AF6_rosnandoEntities()
            : base("name=DB_A41AF6_rosnandoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acesso> Acesso { get; set; }
        public virtual DbSet<Animais> Animais { get; set; }
        public virtual DbSet<Dica> Dica { get; set; }
        public virtual DbSet<RacaAnimal> RacaAnimal { get; set; }
        public virtual DbSet<StstusAnimal> StstusAnimal { get; set; }
        public virtual DbSet<TipoAnimal> TipoAnimal { get; set; }
        public virtual DbSet<TipoDica> TipoDica { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
