//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rosnando_semG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RacaAnimal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RacaAnimal()
        {
            this.Animais = new HashSet<Animais>();
        }
    
        public int raca_animal_id { get; set; }
        public string raca_animal_descricao { get; set; }
        public int usuario_id { get; set; }
        public int tipo_animal_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animais> Animais { get; set; }
        public virtual TipoAnimal TipoAnimal { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
